services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    env_file:
      - .env  

    command: poetry run streamlit run app.py --server.port=8501